[package]
name = "bm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
chrono = "0.4.22"
ron = "0.8.0"
serde = { version = "1", features = ["derive"] }
url = "2.3.1"
